enum LogisticsType { LOCKER_TO_LOCKER, HOME_TO_LOCKER }

enum OrderStatus {
  PENDING,
  AWAITING_COURIER,
  AWAITING_PICKUP,
  ACTIVE,
  COMPLETED,
  LOCKED_BY_BALANCE,
  CANCELLED,
}

enum OrderDetailStatus {
  PENDING,
  AWAITING_COURIER,
  AWAITING_PICKUP,
  AWAITING_CONFIRM_DEPOSIT,
  IN_TRANSIT,
  OCCUPIED,
  COMPLETED,
  OVERDUE,
  COLLECTING,
  COLLECTED,
  AWAITING_DROP,
  CANCELLED,
}

enum PaymentStatus { PENDING, UNPAID, PAID, PARTIAL_PAID, REFUNDED }

enum TransactionType {
  DEPOSIT,
  RENTAL_DEDUCTION,
  LOGISTICS_DEDUCTION,
  OVERDUE_PENALTY,
  REFUND,
  TOP_UP,
  WITHDRAW,
}

enum TransactionStatus { SUCCESS, FAILED, PENDING, CANCELLED }

enum OrderType { LOGISTICS, PERSONAL_RENTAL }

enum ItemType { FOOD, OTHER }

enum FeeBlockUnit { MINUTE, HOUR, DAY, WEEK, MONTH }
